version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: gem install bundler
          command: gem install bundler
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: テスト実行
          command: bundle exec rspec
